on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '30 3 * * 4'

name: CI

jobs:

  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.73.0
      - run: cargo build
      - run: cargo test --all-features 

  clippy:
    name: run clippy lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.73.0
        with:
          components: clippy
      - run: cargo clippy --all-features -- -D warnings

  fmt:
    name: run rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.73.0
      with:
        components: rustfmt
    - run: cargo fmt --all --check

  audit:
    name: run cargo audit
    runs-on: ubuntu-latest
    container: dbrgn/cargo-audit:latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo audit
